services:
  app:
    image: ghcr.io/data5tream/simple-status-page:latest
    environment:
      - APP_WEBSERVER_URL=http://localhost:8080
    ports:
      - "8080:8080"
    volumes:
      - ./config.toml:/config.toml:ro
