services:
  app:
    image: ghcr.io/data5tream/simple-status-page:latest
    environment:
      # The URL at which the web server is reachable
      APP_WEBSERVER_URL: http://127.0.0.1:8000
    ports:
      - "8000:8000"
    volumes:
      - ./config.toml:/config.toml:ro
