[webserver]
host = "127.0.0.1"
port = 8080

[redis]
url = "redis://127.0.0.1:6379/0"

[watcher]
interval = 30
watchlist = [
    { id = "serv", name = "Local dev", ip = "127.0.0.1", url = "http://localhost:8080/" }
]

[log]
level = "debug"
path = "test.log"
