services:
  redis:
    image: redis:alpine
    networks:
      - backend
  app:
    image: ghcr.io/data5tream/status-page-test:latest
    ports:
      - 8080:8080
    networks:
      - default
      - backend
    volumes:
      - ./config.toml:/config.toml
networks:
  default:
  backend:
