name: Lint frontend

on:
  push:
    paths:
      - 'frontend/**'

permissions:
  checks: write

jobs:
  run-frontend-linters:
    name: Run frontend linters
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v6

      - name: Setup deno
        uses: denoland/setup-deno@v2

      - name: Check lints
        run: deno lint

      - name: Check format
        run: deno fmt --check

      - name: Run stylelint
        run: deno task lint:styles
