name: Lint backend

on:
  push:
    paths-ignore:
      - '**.md'
      - 'frontend'

permissions:
  checks: write

jobs:
  run-backend-linter:
    name: Run backend linter
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install toolchain
        run: rustup show active-toolchain

      - name: Build app
        run: cargo clippy
